# site settings
title: CYL
subtitle: UX Researcher. Non-profit Consultant. Writer.
email: mailto:liu.carleen@gmail.com
description: I'm interested in UX, behavioral economics, and social cognition. <br /> You can find my work and writing here.
baseurl: # the subpath of your site, e.g. /blog
url: "carleenyliu.com" # the base hostname & protocol for your site
author: Carleen


# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 4

# social settings
500px_url:
facebook_url:
github_url: https://github.com/carleenliu
gitlab_url: 
googleplus_url:
instagram_url: 
linkedin_url: https://www.linkedin.com/in/carleenliu/
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown
incremental: BOOL

sass:
  style: compressed